# Generated by Django 5.0.1 on 2024-01-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipofii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTipo', models.CharField(default='', max_length=50, verbose_name='Descrição tipo de fundo')),
            ],
            options={
                'db_table': 'tipofii',
                'db_table_comment': 'Tipo de Fundos imobiliarios',
            },
        ),
    ]
