# Generated by Django 5.0.1 on 2024-02-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fii', '0003_alter_fii_datcom_alter_fii_datpag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datPaga', models.DateField(blank=True, null=True, verbose_name='Data do movimento')),
                ('qtdCotas', models.IntegerField(verbose_name='Quantidade de cotas')),
                ('valUnitario', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor unitario do dividendo')),
                ('valTotal', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor Total')),
                ('codFii', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fii.fii', verbose_name='Codigo do fundo imobiliario')),
            ],
            options={
                'db_table': 'dividendo',
                'db_table_comment': 'Dividendos recebidos',
            },
        ),
    ]
