# Generated by Django 5.0.1 on 2024-01-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipofii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fii',
            fields=[
                ('codFii', models.CharField(default='', max_length=6, primary_key=True, serialize=False, verbose_name='Codigo do fundo imobiliario')),
                ('nomFii', models.CharField(default='', max_length=50, verbose_name='Nome do fundo imobiliario')),
                ('qtdCotas', models.IntegerField(verbose_name='Quantidade de cotas')),
                ('valTotal', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Total investido')),
                ('datCom', models.DateField(verbose_name='Data Com')),
                ('datPag', models.DateField(verbose_name='Data de pagamento')),
                ('tipoFii', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipofii.tipofii')),
            ],
            options={
                'db_table': 'fii',
                'db_table_comment': 'Fundos imobiliarios',
            },
        ),
    ]
