# Generated by Django 5.0.1 on 2024-01-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fii', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fii',
            old_name='tipoFii',
            new_name='tipFii',
        ),
    ]
