# Generated by Django 5.0.1 on 2024-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fii', '0002_rename_tipofii_fii_tipfii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fii',
            name='datCom',
            field=models.CharField(max_length=2, verbose_name='Data Com'),
        ),
        migrations.AlterField(
            model_name='fii',
            name='datPag',
            field=models.CharField(max_length=2, verbose_name='Data de pagamento'),
        ),
    ]
