# Generated by Django 5.0.1 on 2024-02-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fii', '0003_alter_fii_datcom_alter_fii_datpag'),
    ]

    operations = [
        migrations.AddField(
            model_name='fii',
            name='codCor',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='fii',
            name='codFii',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='fii',
            name='qtdCotas',
            field=models.IntegerField(null=True, verbose_name='Quantidade de cotas'),
        ),
        migrations.AlterField(
            model_name='fii',
            name='valTotal',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Total investido'),
        ),
    ]
