# Generated by Django 5.0.1 on 2024-02-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fii', '0004_fii_codcor_alter_fii_codfii_alter_fii_qtdcotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fii',
            name='valDividendo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Total dividendos'),
        ),
        migrations.AlterField(
            model_name='fii',
            name='codCor',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='fii',
            name='qtdCotas',
            field=models.IntegerField(default=0, null=True, verbose_name='Quantidade de cotas'),
        ),
        migrations.AlterField(
            model_name='fii',
            name='valTotal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, null=True, verbose_name='Total investido'),
        ),
    ]
