# Generated by Django 5.0.1 on 2024-02-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fii', '0005_fii_valdividendo_alter_fii_codcor_alter_fii_qtdcotas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fii',
            options={'ordering': ['codFii']},
        ),
    ]
