# Generated by Django 5.0.1 on 2024-01-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datMovimento', models.DateField(verbose_name='Data do movimento')),
                ('qtdCotas', models.IntegerField(verbose_name='Informe quantidade')),
                ('valUnitario', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor unitário de cota')),
                ('tipMovimento', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('codFii', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fii.fii', verbose_name='Codigo do fundo imobiliario')),
            ],
            options={
                'db_table': 'movimento',
                'db_table_comment': 'Compra e venda de ativos',
            },
        ),
    ]
