# Generated by Django 5.0.1 on 2024-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='valTotal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Valor Total'),
        ),
    ]
